USE [C:\USERS\ELIAQ\SOURCE\REPOS\ELIAQUIMJORRAS\FUNCAO-SISTEMA-TESTE\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC FI_SP_AltBeneficiario
    @NOME          VARCHAR (50),
	@Id            BIGINT,
	@CPF		   VARCHAR (11)
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		NOME = @NOME,
		CPF = @CPF
	WHERE Id = @Id
END