USE [C:\USERS\ELIAQ\SOURCE\REPOS\ELIAQUIMJORRAS\FUNCAO-SISTEMA-TESTE\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC FI_SP_ListarBeneficiarios
	@IDCLIENTE BIGINT
AS
BEGIN
	SELECT
		ID, 
		CPF ,
		NOME,
		IDCLIENTE
	FROM 
		BENEFICIARIOS WITH(NOLOCK) 
	WHERE
		IDCLIENTE = @IDCLIENTE
END