USE [C:\USERS\ELIAQ\SOURCE\REPOS\ELIAQUIMJORRAS\FUNCAO-SISTEMA-TESTE\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

CREATE OR ALTER PROC FI_SP_VerificaBeneficiario
	@CPF VARCHAR(14)
AS
BEGIN
	SELECT 1 FROM BENEFICIARIOS WHERE CPF = @CPF
END
